[".tmux"]
    type = "archive"
    url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    exact = true
    stripComponents = 1
